### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by RadDemo** [tkarabela/translate-swf#1]
C:\Users\bnico\Desktop\redacted>translateSfw.py gather
Traceback (most recent call last):
  File "C:\Users\bnico\Desktop\redacted\translateSfw.py", line 2, in <module>
    import pyTranslateSwf
  File "C:\Users\bnico\Desktop\redacted\pyTranslateSwf\__init__.py", line 14, in <module>
    from .parsers import Parser, JPEXSPlainTextParser, JPEXSActionScriptParser, get_parsers_for_directory
  File "C:\Users\bnico\Desktop\redacted\pyTranslateSwf\parsers.py", line 53
    def __init__(self, path_or_file: Union[str, io.TextIOBase]):
                                   ^
SyntaxError: invalid syntax

**Comment by tkarabela** [comment]
Hi @ObamaGaming45 , it looks like you're trying to run the script using Python 2.7 - this will not work. Please use Python 3.6 or newer, as specified in the README: https://github.com/tkarabela/translate-swf#installation

**Comment by ObamaGaming45** [comment]
> Hi @ObamaGaming45 , it looks like you're trying to run the script using Python 2.7 - this will not work. Please use Python 3.6 or newer, as specified in the README: https://github.com/tkarabela/translate-swf#installation

C:\Users\bnico\Desktop\redacted>python3 translateSfw.py gather
Warning - 'regex' module is not installed, JPEXSActionScriptParser heuristics will be less effective
Warning - cannot import one of 'stanza', 'jamdict', 'jaconv' modules - OfflineTranslator will not be available
