### ISSUE TITLE
Warning - 'regex' module is not installed.

### ISSUE THREAD

**Issue by RadDemo** [tkarabela/translate-swf#2]
C:\Users\bnico\Desktop\redacted>python3 translateSfw.py gather
Warning - 'regex' module is not installed, JPEXSActionScriptParser heuristics will be less effective
Warning - cannot import one of 'stanza', 'jamdict', 'jaconv' modules - OfflineTranslator will not be available

I have executed the pip install regex command and it did not fix it.

**Comment by tkarabela** [comment]
Hi, I think the issue might be that you now have both Python 2 and 3 in your system, and the `pip` you called was from the Python 2.

Can you try this?

```
python3 -m pip install regex
```

(From what I remember, the `regex` dependency is kind of important to get as many translatable strings as possible; the script will run without it, but not catch as many strings.)

**Comment by RadDemo** [comment]
It worked, thanks. Although it didn't translate most of it, it translated enough.

**Comment by tkarabela** [comment]
Glad to hear you got it working! :)
